export interface Atendimentos {
    id: number,
    atendente: string,
    usina: string,
    solicitante: string,
    dataAtendimento: string,
    horaSolicitado: string,
    inicioDoAtendimento: string,
    fimDoAtendimento: string,
    problemaRelatado: string,
    solucao: string,
    tipoDesvio: string,
    tipoDescarte: string,
    setorMatriz: string,
    tipoChamado: string,
    codContrato: string,
    codTraco: string,
    versao: string,
    tipoComprovante: string,
    valorMargem: string,
    valorComprovante: string,
    aprovado: any,
    gerencia: any,
    dataDoPagamento: string,
    valor_diesel_liberado: string,
    placa: string,
    documento_cliente: number,
    nome_cliente: string,
    banco: string,
    observacao: string,
    valorFixoBomba: number,
    valorMBomba: number,
    tipoBomba: string,
    created_at: string,
    [key: string]: any;
}

export interface AtendimentosLiberacoes {
    id: number,
    atendente: string,
    usina: string,
    solicitante: string,
    dataAtendimento: string,
    inicioDoAtendimento: string,
    fimDoAtendimento: string,
    tipoChamado: string,
    codContrato: string,
    codTraco: string,
    versao: string,
    tipoComprovante: string,
    valorMargem: string,
    valorComprovante: string,
    aprovado: any,
    dataDoPagamento: string,
    [key: string]: any;
}